### ISSUE TITLE
FTB Utilities and Lib?

### ISSUE THREAD

**Issue by rmnaderdev** [TimGoll/EF3#1]
Hello, 

I manage a large modding community called TWPI. We voted on a 3rd server to put up and the Engineer's Forest 3 has won. Would it be possible for you to add FTB Utilities and Lib to the pack? It would really help us with claim protection.

Thank you

**Comment by TimGoll** [comment]
Yes, this would be possible. 
But I'm a bit confused. Who are you? And what for a voting? 
I could publish an update later today (Germany)

**Comment by rmnaderdev** [comment]
Hello,
my name is RJ, I started a modded Minecraft community about a year ago and I run Minecraft servers for the community. We have grown a lot since it first  started. We took a vote for a new modpack server and the community chose Engineer's Forest 3 so we are running it on our server. It would be a little bit easier to manage with FTB Utilities.

**Comment by TimGoll** [comment]
Talked to one of your members on discord.
I'll add it later today. Have fun playing :)

**Comment by TimGoll** [comment]
Added it, now waiting for curse to approve the update. Mekanism is now also included (no beta install needed)

**Comment by rmnaderdev** [comment]
Great!
Thank you very much!
Sorry about the confusion. :)
