### ISSUE TITLE
Two things, not sure if either are intentional

### ISSUE THREAD

**Issue by UncertifiedDevice** [TimGoll/EF3#2]
Not enough wands' wands consume xp by default, can you set them to consume rf instead?
Immersive Engineering Crafting Components blueprint is unobtainable

**Comment by TimGoll** [comment]
Yes it is possible. But you have to wait 2 days until after my Christmas holidays

**Comment by TimGoll** [comment]
okay, I think that I fixed your problems

**Comment by TimGoll** [comment]
okay. Answered before looking into NEW config. I have no idea what I have to change (never used that mod). Should I set xp values to 0 and RF to a specific value?

**Comment by UncertifiedDevice** [comment]
In the notenoughwands.cfg change line 26 
`    S:wandSettingPreset=default` to
`    S:wandSettingPreset=normal_rf` or `hard_rf`
and every wand should be consuming rf

**Comment by TimGoll** [comment]
that's it? nice, thanks!

**Comment by UncertifiedDevice** [comment]
Yeah, just tested, you don't need to change any other value in the config. That one string takes care of it all
