### ISSUE TITLE
[Mod suggestions]

### ISSUE THREAD

**Issue by UncertifiedDevice** [TimGoll/EF3#3]
[Binnie's Mods](https://minecraft.curseforge.com/projects/binnies-mods) - Adds many more bees and trees to forestry as well as a few new machines
[Gendustry](https://minecraft.curseforge.com/projects/gendustry) - Adds some rf powered machines for breeding and keeping bees
[Extra TiC](https://minecraft.curseforge.com/projects/extratic) - Adds many new tinkers parts from made of materials from different mods like mekanism metals

**Comment by TimGoll** [comment]
I'll look into it, thanks :)

**Comment by TimGoll** [comment]
added all of them

**Comment by TimGoll** [comment]
about the third: I added [this one](https://minecraft.curseforge.com/projects/plustic).
