### ISSUE TITLE
[2.1.0] [Crash] Aether Legacy causing crashes when achievements are earned in multiplayer

### ISSUE THREAD

**Issue by JaSpr** [TimGoll/EF3#4]
[Aether Legacy Issue](https://github.com/Modding-Legacy/Aether-Legacy/issues/259)
A fix has been committed, and a new release was issued yesterday:

https://minecraft.curseforge.com/projects/aether-legacy/files/2516932

**Comment by TimGoll** [comment]
Okay, I'll update as soon as possible

**Comment by TimGoll** [comment]
I'll release the update today!
